services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:password@pg-db:5432/postgres
    # depends-on:
    #   - pg-db

  websocket:
    build:
      context: ./
      dockerfile: ./docker/websocket.Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:password@pg-db:5432/postgres
    # depends-on:
    #   - pg-db

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend.Dockerfile
      args:
        DATABASE_URL: $DATABASE_URL
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@pg-db:5432/postgres
    # depends-on:
    #   - pg-db

  pg-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
