name: Deploy Backend

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Code On Machine
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/backend.Dockerfile
          push: true
          tags: mecodes/notes-backend:${{ github.sha }}

      - name: SSH into VM and rerun the docker container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker kill notes-backend # stop container
            docker rm notes-backend # remove container
            docker rmi $(docker images | grep 'notes-backend') # remove images, don't wanna full the space
            docker run --name notes-backend -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -p 4000:4000 -d mecodes/notes-backend:${{ github.sha }} # running in detached mode so action stops after starting the container
