name: Deploy Frontend

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/web.Dockerfile
          push: true
          tags: mecodes/notes-frontend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: SSH into EC2 and restart Docker Container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker kill notes-frontend -f # stop container
            docker rm notes-frontend -f # remove container
            docker rmi $(docker images | grep 'notes-frontend') # remove image
            docker run --name notes-frontend -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -p 3000:3000 mecodes/notes-frontend:${{ github.sha }}
