name: Deploy WebSocket Server

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/websocket.Dockerfile
          push: true
          tags: mecodes/notes-websocket:${{ github.sha }}

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker kill notes-websocket -f # stop container
            docker rm notes-websocket -f # remove container
            docker rmi $(docker images | grep 'notes-websocket') # remove images
            docker run --name notes-websocket -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -p 8080:8080 -d mecodes/notes-websocket:${{ github.sha }}
